apply plugin: 'com.android.application'

configurations.all {
    resolutionStrategy {
        force "androidx.core:core:1.12.0"
        force "androidx.core:core-ktx:1.12.0"
        force "androidx.activity:activity:1.7.2"
        
        // Resolve conflitos de classes duplicadas do Kotlin (stdlib-jdk7/jdk8)
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.jetbrains.kotlin') {
                details.useVersion rootProject.ext.kotlinVersion
            }
        }
    }
}

android {
    namespace "com.ciep165.app"
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.ciep165.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$rootProject.ext.androidxAppCompatVersion"
    implementation "androidx.core:core:$rootProject.ext.androidxCoreVersion"
    implementation "androidx.activity:activity:$rootProject.ext.androidxActivityVersion"
    
    // Força a unificação da stdlib para evitar Duplicate Class
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:${rootProject.ext.kotlinVersion}") {
            because("kotlin-stdlib-jdk7 is now part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${rootProject.ext.kotlinVersion}") {
            because("kotlin-stdlib-jdk8 is now part of kotlin-stdlib")
        }
    }
}

apply from: 'capacitor.build.gradle'