apply plugin: 'com.android.application'

android {
    namespace "com.ciep165.app"
    compileSdk project.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.ciep165.app"
        minSdk project.ext.minSdkVersion
        targetSdk project.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    flatDir{
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "androidx.appcompat:appcompat:$project.ext.androidxAppCompatVersion"
    implementation "androidx.core:core:$project.ext.androidxCoreVersion"
    implementation project(':capacitor-android')
}

apply from: 'capacitor.build.gradle'